// svelte-app/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  let message = 'Hello from Svelte!';
  let backendMessage = 'Loading...';

  onMount(async () => {
    try {
      const response = await fetch('/api/svelte-data');
      if (response.ok) {
        const data = await response.json();
        backendMessage = data.message;
      } else {
        backendMessage = 'Failed to load data from backend.';
        console.error('Failed to load data:', response.statusText);
      }
    } catch (error) {
      backendMessage = 'Error fetching data.';
      console.error('Error fetching data:', error);
    }
  });
</script>

<main>
  <h1>Svelte App</h1>
  <p>{message}</p>
  <p>Message from Backend: {backendMessage}</p>
</main>

<style>
  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }
  h1 {
    color: #ff3e00; /* Svelte orange */
    text-transform: uppercase;
    font-size: 3em; /* Adjusted for manual setup */
    font-weight: 100;
  }
</style>

// react-app/src/App.tsx
import { useEffect, useState } from 'react';
import './App.css';

function App() {
  const [message, setMessage] = useState('');
  const [backendMessage, setBackendMessage] = useState('');

  useEffect(() => {
    setMessage('Hello from React!');

    // Fetch data from the Bun backend
    fetch('/api/react-data')
      .then(response => response.json())
      .then(data => setBackendMessage(data.message))
      .catch(error => console.error('Error fetching data:', error));
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <h1>React App</h1>
        <p>{message}</p>
        <p>Message from Backend: {backendMessage}</p>
      </header>
    </div>
  );
}

export default App;
